/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/models/shoe-draco.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../contexts/Customization'

export function Shoe(props) {
  const { nodes, materials } = useGLTF('/models/shoe-draco.glb')
  const { mainColor, mainColorsPalette } = useCustomization()

  return (
    <group {...props} dispose={null} scale={0.4} rotation={[0, 0, - Math.PI / 0.45]} position-y={0.25}>
      <mesh castShadow geometry={nodes.shoe.geometry} material={materials.laces} />
      <mesh castShadow geometry={nodes.shoe_1.geometry} material={materials.mesh} />
      <mesh castShadow geometry={nodes.shoe_2.geometry} material={materials.caps} material-color={mainColorsPalette[mainColor]} />
      <mesh castShadow geometry={nodes.shoe_3.geometry} material={materials.inner} material-color={mainColorsPalette[mainColor]} />
      <mesh castShadow geometry={nodes.shoe_4.geometry} material={materials.sole} material-color={mainColorsPalette[mainColor]} />
      <mesh castShadow geometry={nodes.shoe_5.geometry} material={materials.stripes} />
      <mesh castShadow geometry={nodes.shoe_6.geometry} material={materials.band} material-color={mainColorsPalette[mainColor]} />
      <mesh castShadow geometry={nodes.shoe_7.geometry} material={materials.patch} />
    </group>
  )
}

useGLTF.preload('/models/shoe-draco.glb')
